# Generated by Django 5.1.5 on 2025-02-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.PositiveIntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.FloatField(),
        ),
    ]
